export const LEVEL_SET = 'LEVEL_SET';
export const LEVEL_UPDATE_STATUS = 'LEVEL_UPDATE_STATUS';
export const RESET_PROGRESS = 'RESET_PROGRESS';
export const ANIMATION_START = 'ANIMATION_START';
export const ANIMATION_STOP = 'ANIMATION_STOP';
export const SET_IS_COMPLETED = 'SET_IS_COMPLETED';
