version: '3.9'
services:
  web:
    image: 14.17-alpine3.11
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
    command: sh -c "cd /app; yarn install; yarn run start:dev --host 0.0.0.0"
