version: '3.9'
services:
  web:
    build:
      context: ./
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
    command: 'yarn run start --host 0.0.0.0'
